name: Say hello

on:
  push:
    branches:
      - main

jobs:
  hello_world:
    runs-on: self-hosted
    steps:
      - name: Echo the message
        run: |
          echo "Hola Chaval3!"
      - name: Dime la fecha
        run: date
      - run: ls -l